version: '3.1'
services:
    redis:
        image: redis:alpine
        ports:
          - 6379:6379

    mailpit:
        image: axllent/mailpit
        ports:
          - 1025:1025
          - 8025:8025
